### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by Teles1** [laktek/uniswap-v3-pools#9] opened 2021-12-24 15:28 UTC
running yarn start

![image](https://user-images.githubusercontent.com/66783472/147362088-db75a2b5-0a61-490f-bbc0-ff9ddcb72839.png)

`D:/uniswap-v3-pools/src/types/v3/index.ts
TypeScript error in D:/uniswap-v3-pools/src/types/v3/index.ts(undefined,undefined):
'index.ts' cannot be compiled under '--isolatedModules' because it is considered a global script file. Add an import, export, or an empty 'export {}' statement to make it a module.  TS1208`

I'm running node v16.13.1 and yarn 1.22.15
This is a completely fresh clone. No changes made other than -> 
`"compile-v3-contract-types": "yarn typechain --target ethers-v5 --out-dir src/types/v3 './node_modules/@uniswap/?(v3-core|v3-periphery)/artifacts/contracts/**/*.json'",` to ->
`"compile-v3-contract-types": "yarn typechain --target ethers-v5 --out-dir src/types/v3 './node_modules/@uniswap/v3-core/artifacts/contracts/**/*.json'",`
under package.json

**Comment by laktek** [comment] 2021-12-25 08:53
Did you do a yarn install before trying `yarn start`?

**Comment by Teles1** [comment] 2021-12-25 15:11
Yes. I even get confirmation saying that all modules are installed

Henrique Teles,
Software Developer
(647-641-0411)

**Comment by laktek** [comment] 2022-01-06 10:41
Sorry, can't reproduce this issue. Closing this.

**Closed by laktek** 2022-01-06 10:41 UTC
